import Head from 'next/head'
import MRC721 from '../src/components/Mrc721'

export default function Home() {
  return (
    <>
      <Head>
        <title>Muon MRC721</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MRC721 />
    </>
  )
}
